services:
  mongodb:
    image: mongo:latest
    container_name: allcash-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=allcash

volumes:
  mongodb_data: