services:
  app:
    image: ghcr.io/kaympe20/allcash:main
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=allcash
    restart: unless-stopped

volumes:
  mongodb_data: